name: release
on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOROOT: ${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'
      - name: Run tests
        run: |
          go get .
          go test test/*

